# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ilya/CProjects/ValidBraces

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ilya/CProjects/ValidBraces

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilya/CProjects/ValidBraces/CMakeFiles /home/ilya/CProjects/ValidBraces//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ilya/CProjects/ValidBraces/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stack

# Build rule for target.
stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stack
.PHONY : stack

# fast build rule for target.
stack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/build
.PHONY : stack/fast

#=============================================================================
# Target rules for targets named validbraces_core

# Build rule for target.
validbraces_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 validbraces_core
.PHONY : validbraces_core

# fast build rule for target.
validbraces_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validbraces_core.dir/build.make CMakeFiles/validbraces_core.dir/build
.PHONY : validbraces_core/fast

#=============================================================================
# Target rules for targets named ValidBraces

# Build rule for target.
ValidBraces: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ValidBraces
.PHONY : ValidBraces

# fast build rule for target.
ValidBraces/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ValidBraces.dir/build.make CMakeFiles/ValidBraces.dir/build
.PHONY : ValidBraces/fast

#=============================================================================
# Target rules for targets named test_stack

# Build rule for target.
test_stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stack
.PHONY : test_stack

# fast build rule for target.
test_stack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stack.dir/build.make CMakeFiles/test_stack.dir/build
.PHONY : test_stack/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

libs/stack.o: libs/stack.c.o
.PHONY : libs/stack.o

# target to build an object file
libs/stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/libs/stack.c.o
.PHONY : libs/stack.c.o

libs/stack.i: libs/stack.c.i
.PHONY : libs/stack.i

# target to preprocess a source file
libs/stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/libs/stack.c.i
.PHONY : libs/stack.c.i

libs/stack.s: libs/stack.c.s
.PHONY : libs/stack.s

# target to generate assembly for a file
libs/stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stack.dir/build.make CMakeFiles/stack.dir/libs/stack.c.s
.PHONY : libs/stack.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validbraces_core.dir/build.make CMakeFiles/validbraces_core.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ValidBraces.dir/build.make CMakeFiles/ValidBraces.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validbraces_core.dir/build.make CMakeFiles/validbraces_core.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ValidBraces.dir/build.make CMakeFiles/ValidBraces.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validbraces_core.dir/build.make CMakeFiles/validbraces_core.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ValidBraces.dir/build.make CMakeFiles/ValidBraces.dir/src/main.c.s
.PHONY : src/main.c.s

tests/test_main.o: tests/test_main.c.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/tests/test_main.c.o
.PHONY : tests/test_main.c.o

tests/test_main.i: tests/test_main.c.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/tests/test_main.c.i
.PHONY : tests/test_main.c.i

tests/test_main.s: tests/test_main.c.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/tests/test_main.c.s
.PHONY : tests/test_main.c.s

tests/test_stack_library.o: tests/test_stack_library.c.o
.PHONY : tests/test_stack_library.o

# target to build an object file
tests/test_stack_library.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stack.dir/build.make CMakeFiles/test_stack.dir/tests/test_stack_library.c.o
.PHONY : tests/test_stack_library.c.o

tests/test_stack_library.i: tests/test_stack_library.c.i
.PHONY : tests/test_stack_library.i

# target to preprocess a source file
tests/test_stack_library.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stack.dir/build.make CMakeFiles/test_stack.dir/tests/test_stack_library.c.i
.PHONY : tests/test_stack_library.c.i

tests/test_stack_library.s: tests/test_stack_library.c.s
.PHONY : tests/test_stack_library.s

# target to generate assembly for a file
tests/test_stack_library.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stack.dir/build.make CMakeFiles/test_stack.dir/tests/test_stack_library.c.s
.PHONY : tests/test_stack_library.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ValidBraces"
	@echo "... stack"
	@echo "... test_main"
	@echo "... test_stack"
	@echo "... validbraces_core"
	@echo "... libs/stack.o"
	@echo "... libs/stack.i"
	@echo "... libs/stack.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
	@echo "... tests/test_stack_library.o"
	@echo "... tests/test_stack_library.i"
	@echo "... tests/test_stack_library.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

